package com.example.graduationdesign.tool;

/**
 * Created by zy on 2017/2/16.
 */

public class StringsData2 {
    public static final String data = "{" +
            "'number':1," +
            "'resultquestiondata':[" +
            "{" +
            "'question_id':'1'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第一章'," +
            "'question':''," +
            "'question_number':'3'," +
            "'question_option_a':'选项A'," +
            "'question_option_b':'选项B'," +
            "'question_option_c':'选项C'," +
            "'question_option_d':'选项D'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'100'," +
            "'answer_analysis':'这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'2'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第一章'," +
            "'question':''," +
            "'question_number':'3'," +
            "'question_option_a':'选项A'," +
            "'question_option_b':'选项B'," +
            "'question_option_c':'选项C'," +
            "'question_option_d':'选项D'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'100'," +
            "'answer_analysis':'这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'11098'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第六章'," +
            "'question':'这是马渊第六章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'11134'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第一章'," +
            "'question':'这是马渊第一章第一道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'11469'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第一章'," +
            "'question':'这是马渊第一章第一道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'11790'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第六章'," +
            "'question':'这是马渊第六章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'11793'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第六章'," +
            "'question':'这是马渊第六章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'11886'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第六章'," +
            "'question':'这是马渊第六章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'12087'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第三章'," +
            "'question':'这是马渊第三章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'12279'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第七章'," +
            "'question':'这是马渊第七章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'12287'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第三章'," +
            "'question':'这是马渊第三章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'12554'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第七章'," +
            "'question':'这是马渊第七章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'12683'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第三章'," +
            "'question':'这是马渊第三章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'13205'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第八章'," +
            "'question':'这是马渊第八章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'13383'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第四章'," +
            "'question':'这是马渊第四章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'13589'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第二章'," +
            "'question':'这是马渊第二章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'13812'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第一章'," +
            "'question':'这是马渊第一章第一道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'14312'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第一章'," +
            "'question':'这是马渊第一章第一道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'14325'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第四章'," +
            "'question':'这是马渊第四章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}," +
            "{" +
            "'question_id':'14394'," +
            "'question_subject':'马原'," +
            "'question_chapter':'第四章'," +
            "'question':'这是马渊第四章第XX道题'," +
            "'question_number':'0'," +
            "'question_option_a':'question_option_a选项a'," +
            "'question_option_b':'question_option_b选项B'," +
            "'question_option_c':'question_option_c选项c'," +
            "'question_option_d':'question_option_d选项d'," +
            "'answer':'1'," +
            "'difficulty_level':'2'," +
            "'comment_number':'0'," +
            "'answer_analysis':'answer_analysis这道题全靠蒙，别想那么多'" +
            "}" +
            "]" +
            "}";

}
